{
 "title": "V5 Dedicated Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "resource_id",
    "label": "resource_id",
    "query": {
     "query": "label_values(deployment_emqx_resource_status,resource_id)"
    }
   },
   { "name": "rule_id", "label": "rule_id", "query": { "query": "label_values(rule_id)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_live_connections_count",
     "legendFormat": "Live Connections Count"
    },
    { "expr": "deployment_emqx_sessions_count", "legendFormat": "Connection Sessions Count" }
   ]
  },
  {
   "title": "Message Rate",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deployment_emqx_messages_rate", "legendFormat": "Messages Rate" },
    {
     "expr": "deployment_emqx_messages_send_rate",
     "legendFormat": "Send Rate"
    },
    {
     "expr": "deployment_emqx_messages_receive_rate",
     "legendFormat": "Receive Rate"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_topics_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscriptions_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_retained_count",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Sent Bytes Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_bytes_sent[$__interval])",
     "legendFormat": "Bytes Sent"
    }
   ]
  },
  {
   "title": "Received Bytes Timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_bytes_received[$__interval])",
     "legendFormat": "Bytes Received"
    }
   ]
  },
  {
   "title": "Messages Received (by EMQX) Timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Received Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_messages_received[$__interval])",
     "legendFormat": "Messages Received"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_qos0_received[$__interval])",
     "legendFormat": "Messages QoS0 Received"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_qos1_received[$__interval])",
     "legendFormat": "Messages QoS1 Received"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_qos2_received[$__interval])",
     "legendFormat": "Messages Qos2 Received"
    }
   ]
  },
  {
   "title": "Messages Dropped in Received Phrase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_messages_dropped[$__interval])",
     "legendFormat": "Messages Dropped"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_dropped_expired[$__interval])",
     "legendFormat": "Messages Dropped Expired"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_dropped_no_subscribers[$__interval])",
     "legendFormat": "Messages Dropped No Subscribers"
    }
   ]
  },
  {
   "title": "Messages Sent (By EMQX) Timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Sent Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_messages_sent[$__interval])",
     "legendFormat": "Messages Sent"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_qos0_sent[$__interval])",
     "legendFormat": "Messages QoS0 Sent"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_qos1_sent[$__interval])",
     "legendFormat": "Messages Qos1 Sent"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_qos2_sent[$__interval])",
     "legendFormat": "Messages QoS2 Sent"
    }
   ]
  },
  {
   "title": "Messages Dropped in Sent Phrase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped[$__interval])",
     "legendFormat": "Delivery Dropped"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_too_large[$__interval])",
     "legendFormat": "Delivery Dropped Too Large"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_queue_full[$__interval])",
     "legendFormat": "Delivery Dropped Queue Full"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_no_local[$__interval])",
     "legendFormat": "Delivery Dropped No Local"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_expired[$__interval])",
     "legendFormat": "Delivery Dropped Expired"
    }
   ]
  },
  { "title": "Topics and Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_topics_count",
     "legendFormat": "Topics Count"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscriptions_count",
     "legendFormat": "Subscriptions Count"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscribers_count",
     "legendFormat": "Subscribers Count"
    }
   ]
  },
  {
   "title": "Shared Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscriptions_shared_count",
     "legendFormat": "Subscriptions Shared Count"
    }
   ]
  },
  {
   "title": "Authentication and Authorization ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_authentication_success[$__interval])",
     "legendFormat": "Authentication Success"
    },
    {
     "expr": "increase(deployment_emqx_metrics_authentication_failure[$__interval])",
     "legendFormat": "Authentication Failure"
    }
   ]
  },
  {
   "title": "Authorization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_client_authorize[$__interval])",
     "legendFormat": "Client Authorize"
    },
    {
     "expr": "increase(deployment_emqx_metrics_authorization_allow[$__interval])",
     "legendFormat": "Authorization Allow"
    },
    {
     "expr": "increase(deployment_emqx_metrics_authorization_deny[$__interval])",
     "legendFormat": "Authorization Deny"
    },
    {
     "expr": "increase(deployment_emqx_metrics_authorization_matched_allow[$__interval])",
     "legendFormat": "Authorization Matched Allow"
    },
    {
     "expr": "increase(deployment_emqx_metrics_authorization_matched_deny[$__interval])",
     "legendFormat": "Authorization Matched Deny"
    },
    {
     "expr": "increase(deployment_emqx_metrics_authorization_nomatch[$__interval])",
     "legendFormat": "Authorization No Match"
    }
   ]
  },
  { "title": "Packets Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_received[$__interval])",
     "legendFormat": "Packets Received"
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_sent[$__interval])",
     "legendFormat": "Packets Sent"
    }
   ]
  },
  {
   "title": "Packets Connack Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_connack_sent[$__interval])",
     "legendFormat": "Packets Connack Sent"
    }
   ]
  },
  {
   "title": "Packets Connect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_connect[$__interval])",
     "legendFormat": "Packets Connect"
    }
   ]
  },
  {
   "title": "Packets Disconnect Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_disconnect_received[$__interval])",
     "legendFormat": "Packets Disconnect Received"
    }
   ]
  },
  {
   "title": "Packets Disconnect Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_disconnect_sent[$__interval])",
     "legendFormat": "Packets Disconnect Sent"
    }
   ]
  },
  {
   "title": "Packets Publish Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_publish_received[$__interval])",
     "legendFormat": "Packets Publish Received"
    }
   ]
  },
  {
   "title": "Packets Publish Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_publish_sent[$__interval])",
     "legendFormat": "Packets Publish Sent"
    }
   ]
  },
  {
   "title": "Packets Subscribe Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_subscribe_received[$__interval])",
     "legendFormat": "Packets Subscribe Received"
    }
   ]
  },
  {
   "title": "Packets Unsubscribe Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_unsubscribe_received[$__interval])",
     "legendFormat": "Packets Unsubscribe Received"
    }
   ]
  },
  {
   "title": "Packets Ping Req Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_pingreq_received[$__interval])",
     "legendFormat": "Packets Ping Req Received"
    }
   ]
  },
  {
   "title": "Packets Ping Resp Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_pingresp_sent[$__interval])",
     "legendFormat": "Packets Ping Resp Sent"
    }
   ]
  },
  {
   "title": "Packets Auth Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_auth_received[$__interval])",
     "legendFormat": "Packets Auth Received"
    }
   ]
  },
  {
   "title": "Packets Auth Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_packets_auth_sent[$__interval])",
     "legendFormat": "Packets Auth Sent"
    }
   ]
  },
  { "title": "Data Integration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Resource Status ($resource_id)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_resource_status{resource_id=\"$resource_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Status ($rule_id)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_rule_status{rule_id=\"$rule_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rule Metrics ($rule_id)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_rule_matched_count{rule_id=\"$rule_id\"}",
     "legendFormat": "Matched ({{match_status}})"
    },
    {
     "expr": "deployment_emqx_rule_action_execution_count{rule_id=\"$rule_id\"}",
     "legendFormat": "Action Execution ({{execution_status}})"
    }
   ]
  }
 ]
}