{
 "title": "EMQX Cloud v4 Deployment Metrics",
 "tags": [
  "EMQX",
  "Dedicated",
  "SRE",
  "v4"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "Platform",
    "label": "Platform",
    "query": {
     "query": "label_values(deployment_emqx_cluster_status,platform)"
    }
   },
   {
    "name": "Type",
    "label": "Type",
    "query": {
     "query": "label_values(deployment_emqx_cluster_status{platform=\"$Platform\"},deployment_type)"
    }
   },
   {
    "name": "ID",
    "label": "ID",
    "query": {
     "query": "label_values(deployment_emqx_cluster_status{platform=\"$Platform\", deployment_type=\"$Type\"},deployment_id)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Deployment $ID" } },
  {
   "title": "Sessions",
   "type": "gauge",
   "description": "Current number of sessions",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_sessions_count{deployment_id=\"$ID\"}",
     "legendFormat": "sub_count"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(deployment_emqx_metrics_messages_sent{deployment_id=\"$ID\"}[1m]))\n+ \nsum (rate(deployment_emqx_metrics_messages_received{deployment_id=\"$ID\"}[1m]))\n+\nsum ((rate(deployment_emqx_rule_action_execution_count{deployment_id=\"$ID\",execution_status=\"taken\"}[1m])) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "gauge",
   "description": "Current number of subscriptions",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscriptions_count{deployment_id=\"$ID\"}",
     "legendFormat": "sub_count"
    }
   ]
  },
  {
   "title": "Shared Subscriptions",
   "type": "gauge",
   "description": "Current number of shared subscriptions",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscriptions_shared_count{deployment_id=\"$ID\"}",
     "legendFormat": "sub_shared_count"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "gauge",
   "description": "Current number of topics",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_topics_count{deployment_id=\"$ID\"}",
     "legendFormat": "topics"
    }
   ]
  },
  {
   "title": "Retained messages",
   "type": "gauge",
   "description": "Current number of retained messages",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_retained_count{deployment_id=\"$ID\"}",
     "legendFormat": "retained"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "deployment_emqx_sessions_count{deployment_id=\"$ID\"}",
     "legendFormat": "Concurrent sessions"
    },
    {
     "expr": "deployment_emqx_connections_count{deployment_id=\"$ID\"}",
     "legendFormat": "Online sessions"
    },
    {
     "expr": "deployment_emqx_sessions_count{deployment_id=\"$ID\"}-deployment_emqx_connections_count{deployment_id=\"$ID\"}",
     "legendFormat": "Offline sessions"
    }
   ]
  },
  {
   "title": "Connection Activities",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_client_connect{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Connect"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_connack{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Connack"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_connected{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Connected"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_disconnected{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Disconnected"
    }
   ]
  },
  {
   "title": "Messages TPS/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(deployment_emqx_metrics_messages_received{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Received messages"
    },
    {
     "expr": "rate(deployment_emqx_metrics_messages_sent{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Sent messages"
    },
    {
     "expr": "rate(deployment_emqx_metrics_messages_sent{deployment_id=\"$ID\"}[1m]) \n+ \nrate(deployment_emqx_metrics_messages_received{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Total messages"
    }
   ]
  },
  {
   "title": "Data Integration TPS/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (execution_status) (rate(deployment_emqx_rule_action_execution_count{deployment_id=\"$ID\"}[1m]))",
     "legendFormat": "{{execution_status}}"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_messages_received{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Inbound messages"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_sent{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Outbound messages"
    },
    {
     "expr": "increase(deployment_emqx_metrics_messages_dropped_no_subscribers{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Messages with no subscribers"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_queue_full{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Queue Full"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_expired{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Expired"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_no_local{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "No Local"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_qos0_msg{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "QoS 0"
    },
    {
     "expr": "increase(deployment_emqx_metrics_delivery_dropped_too_large{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Too Large"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_subscriptions_count{deployment_id=\"$ID\"}",
     "legendFormat": "Number of subscriptions"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "deployment_emqx_metrics_topics_count{deployment_id=\"$ID\"}",
     "legendFormat": "Number of topics"
    }
   ]
  },
  {
   "title": "Subscription Activities",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_client_subscribe{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Subscribe"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_unsubscribe{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Unsubscribe"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(deployment_emqx_metrics_bytes_received{deployment_id=\"$ID\"}[$__rate_interval])",
     "legendFormat": "Received(/s)"
    },
    {
     "expr": "rate(deployment_emqx_metrics_bytes_sent{deployment_id=\"$ID\"}[$__rate_interval])",
     "legendFormat": "Sent(/s)"
    }
   ]
  },
  {
   "title": "Client Authentication",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_client_auth_success{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_auth_failure{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Failure"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_auth_success_anonymous{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Anonymous success"
    }
   ]
  },
  {
   "title": "Client ACL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(deployment_emqx_metrics_client_acl_allow{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Allow"
    },
    {
     "expr": "increase(deployment_emqx_metrics_client_acl_deny{deployment_id=\"$ID\"}[1m])",
     "legendFormat": "Deny"
    }
   ]
  },
  {
   "title": "Rule Status",
   "type": "gauge",
   "description": "The current status of rules",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(deployment_emqx_rule_status{deployment_id=\"$ID\"} == 1) or vector(0)",
     "legendFormat": "enabled"
    },
    {
     "expr": "sum(deployment_emqx_rule_status{deployment_id=\"$ID\"} == bool 0) or vector(0)",
     "legendFormat": "disabled"
    }
   ]
  },
  {
   "title": "Resource Status",
   "type": "gauge",
   "description": "The current status of resources",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(deployment_emqx_resource_status{deployment_id=\"$ID\"} == 1) or vector(0)",
     "legendFormat": "available"
    },
    {
     "expr": "sum(deployment_emqx_resource_status{deployment_id=\"$ID\"} == bool 0) or vector(0)",
     "legendFormat": "not available"
    }
   ]
  },
  {
   "title": "Rule Status List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "deployment_emqx_rule_status{deployment_id=\"$ID\"}",
     "legendFormat": "{{rule_id}}"
    }
   ]
  },
  {
   "title": "Resource Status List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "deployment_emqx_resource_status{deployment_id=\"$ID\"}",
     "legendFormat": "{{resource_id}}"
    }
   ]
  },
  {
   "title": "Action Execution",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(execution_status) (rate(deployment_emqx_rule_action_execution_count{deployment_id=\"$ID\"}[1m]))",
     "legendFormat": "{{execution_status}}"
    }
   ]
  }
 ]
}